{% set version = "isis6" %} # synched up to isis dependencies for this version

package:
    name: s2p-subset
    version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/s2p.git
  git_tag: afd6aa4

build:
    number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - libgcc-ng >=9.3.0    # [linux]
    - libstdcxx-ng >=9.3.0 # [linux] 
    - llvm-openmp >=12.0.1 # [osx] 
    - fftw          3.3.8
    - jpeg 9*
    - libpng 1.6.37
    - libtiff 4.0.10.*
    - libtiff >=4.0.10,<5.0a0
    - openjpeg 2.3.0
    - zlib 1.2.11.*
    - zstd
 
  run:
    - libgcc-ng >=9.3.0    # [linux]
    - libstdcxx-ng >=9.3.0 # [linux] 
    - llvm-openmp >=12.0.1 # [osx] 
    - fftw          3.3.8
    - jpeg 9*
    - libpng 1.6.37
    - libtiff 4.0.10.*
    - libtiff >=4.0.10,<5.0a0
    - openjpeg 2.3.0
    - zlib 1.2.11.*
    - zstd
 
test:
    files:
        imports:
        commands:
        comment:

about:
    home:
    license: APACHE II
    summary:

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
