{% set version = "isis5.0.1_bugfix" %} # synched up to isis dependencies for this version

package:
    name: s2p-subset
    version: {{ version }}

source:
  git_url: git@github.com:oleg-alexandrov/s2p.git
  git_tag: 55e37df

build:
    number: 0

requirements:
    build:
# Use the local compiler for OSX. See build.sh for details.
        - {{ compiler('c') }}     # [linux]
        - {{ compiler('cxx') }}   # [linux]
        - cmake
        - llvm-openmp             # [osx]
        - _libgcc_mutex             0.1            # [linux]
        - gcc_impl_linux-64         7.5.0          # [linux]
        - gcc_linux-64              7.5.0          # [linux]
        - libgcc                    7.2.0          # [linux]
        - libgcc-devel_linux-64     7.5.0          # [linux]
        - libgcc-ng                 11.1.0         # [linux]

    host:
        - _libgcc_mutex             0.1            # [linux]
        - gcc_impl_linux-64         7.5.0          # [linux]
        - gcc_linux-64              7.5.0          # [linux]
        - krb5                      1.16.3         # [linux]
        - libgcc                    7.2.0          # [linux]
        - libgcc-devel_linux-64     7.5.0          # [linux]
        - libgcc-ng                 11.1.0         # [linux]
        - ncurses                   6.2            # [linux]
        - openssl                   1.0.2u         # [linux]
        - python                    3.6.7          # [linux]
        - python-dateutil           2.8.2          # [linux]
        - python_abi                3.6            # [linux]
        - jpeg 9d
        - openjpeg 2.1.0
        - libpng 1.6.37
        - libtiff 4.0.10
        - zlib 1.2.11
        - fftw

    run:
        - _libgcc_mutex             0.1            # [linux]
        - gcc_impl_linux-64         7.5.0          # [linux]
        - gcc_linux-64              7.5.0          # [linux]
        - krb5                      1.16.3         # [linux]
        - libgcc                    7.2.0          # [linux]
        - libgcc-devel_linux-64     7.5.0          # [linux]
        - libgcc-ng                 11.1.0         # [linux]
        - ncurses                   6.2            # [linux]
        - openssl                   1.0.2u         # [linux]
        - python                    3.6.7          # [linux]
        - python-dateutil           2.8.2          # [linux]
        - python_abi                3.6            # [linux]
        - jpeg 9d
        - openjpeg 2.1.0
        - libpng 1.6.37
        - libtiff 4.0.10
        - zlib 1.2.11
        - fftw

test:
    files:
        imports:
        commands:
        comment:

about:
    home:
    license: APACHE II
    summary:

extra:
  recipe-maintainers:
    - oleg.alexandrov@gmail.com
